/**
 * Generated by orval 🍺
 * Do not edit manually.
 * where-to-live
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

export type SystemHealth200 = {[key: string]: string};

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getSystemHealthUrl = () => {




  return `/api/health`
}

/**
 * @summary Health
 */
export const systemHealth = async ( options?: RequestInit): Promise<SystemHealth200> => {

  const res = await fetch(getSystemHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: SystemHealth200 = body ? JSON.parse(body) : {}
  return data
}





export const getSystemHealthQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }


export const getSystemHealthQueryOptions = <TData = Awaited<ReturnType<typeof systemHealth>>, TError = globalThis.Error & { info?: unknown; status?: number }>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof systemHealth>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSystemHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof systemHealth>>> = ({ signal }) => systemHealth({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof systemHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SystemHealthQueryResult = NonNullable<Awaited<ReturnType<typeof systemHealth>>>
export type SystemHealthQueryError = globalThis.Error & { info?: unknown; status?: number }


export function useSystemHealth<TData = Awaited<ReturnType<typeof systemHealth>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof systemHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof systemHealth>>,
          TError,
          Awaited<ReturnType<typeof systemHealth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSystemHealth<TData = Awaited<ReturnType<typeof systemHealth>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof systemHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof systemHealth>>,
          TError,
          Awaited<ReturnType<typeof systemHealth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSystemHealth<TData = Awaited<ReturnType<typeof systemHealth>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof systemHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useSystemHealth<TData = Awaited<ReturnType<typeof systemHealth>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof systemHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSystemHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
